import type { Deal, Corner } from "./types";

/**
 * 真实历史案例库
 * 单位：百万美元 ($M)
 * outcome:
 *   - "win"  IPO 或被高价收购，multiplier 通常 5-20x
 *   - "mid"  中等退出，multiplier 0.8-2.0x
 *   - "loss" 归零或近乎归零，multiplier 0-0.3x
 *
 * 假名 (name) 故意写得像真实 pitch deck 的一句话描述，
 * 让玩家在揭晓前用直觉判断。
 */
export const DEALS: readonly Deal[] = [
  // ================= 大爆款 (WINS) =================
  {
    id: "insta360",
    name: "全景摄像头初创",
    tagline: "一个能 360° 拍摄的小型相机，主打运动和创作者市场",
    tier: "seed", cost: 20, year: 2015, outcome: "win", multiplier: 8,
    real: "Insta360 影石创新",
    story: "你投中了 Insta360。这家公司 2024 年在上交所科创板上市，市值峰值超 700 亿元人民币，成为消费级 360° 相机的全球龙头。",
  },
  {
    id: "bytedance",
    name: "内容推荐算法公司",
    tagline: "用机器学习给每个人推荐他们最想看的内容",
    tier: "a", cost: 50, year: 2014, outcome: "win", multiplier: 12,
    real: "字节跳动 ByteDance",
    story: "你投中了字节跳动。今日头条之后是抖音、TikTok，成为全球最具价值的非上市科技公司之一，估值超 3000 亿美元。",
  },
  {
    id: "airbnb",
    name: "家庭旅馆撮合平台",
    tagline: "让陌生人住进你家的客厅，付钱给你",
    tier: "seed", cost: 20, year: 2009, outcome: "win", multiplier: 10,
    real: "Airbnb",
    story: "YC 时期被无数 VC 拒绝。\"陌生人怎么会愿意住别人家?\" Airbnb 2020 年上市，市值一度突破千亿美元。",
  },
  {
    id: "stripe",
    name: "开发者支付 API",
    tagline: "7 行代码就能让你的网站接受信用卡付款",
    tier: "a", cost: 50, year: 2011, outcome: "win", multiplier: 15,
    real: "Stripe",
    story: "Collison 兄弟做的开发者优先支付平台。一级市场估值峰值 950 亿美元，是金融基础设施领域最成功的初创公司之一。",
  },
  {
    id: "nvidia_early",
    name: "图形芯片公司",
    tagline: "专门做 PC 游戏显卡的半导体公司",
    tier: "a", cost: 50, year: 2003, outcome: "win", multiplier: 20,
    real: "英伟达 NVIDIA",
    story: "当年只是个做游戏显卡的公司。20 年后，AI 浪潮让它成为全球市值最高的公司之一。早期投资人获得了人类金融史上最夸张的回报之一。",
  },
  {
    id: "tesla_early",
    name: "电动跑车公司",
    tagline: "一个硅谷工程师团队要做高端电动车",
    tier: "b", cost: 100, year: 2008, outcome: "win", multiplier: 8,
    real: "特斯拉 Tesla",
    story: "2008 年金融危机时险些破产。Musk 押上全部身家，靠 Roadster 和 Model S 起死回生。如今特斯拉是全球最有价值的车企之一。",
  },
  {
    id: "shopify",
    name: "电商建站工具",
    tagline: "让任何人都能 10 分钟开一家网店",
    tier: "seed", cost: 20, year: 2010, outcome: "win", multiplier: 9,
    real: "Shopify",
    story: "最初是创始人想卖滑雪板找不到合适的电商工具，干脆自己做了一个。如今为全球数百万商家提供服务。",
  },
  {
    id: "pdd",
    name: "拼团购物 App",
    tagline: "让用户拉好友一起买，价格更便宜",
    tier: "seed", cost: 20, year: 2016, outcome: "win", multiplier: 12,
    real: "拼多多 PDD",
    story: "被无数人嘲笑\"消费降级\"和\"五环外\"的拼多多，三年上市，如今市值一度超过阿里巴巴。",
  },
  {
    id: "meituan",
    name: "本地生活团购",
    tagline: "外卖、电影票、酒店预订，所有本地服务一站式",
    tier: "a", cost: 50, year: 2013, outcome: "win", multiplier: 10,
    real: "美团 Meituan",
    story: "千团大战的最终胜出者。2018 年香港上市，如今是中国最大的本地生活服务平台。",
  },
  {
    id: "mihoyo",
    name: "二次元手游团队",
    tagline: "三个上海交大学生做的二次元 RPG 游戏",
    tier: "seed", cost: 20, year: 2014, outcome: "win", multiplier: 15,
    real: "米哈游 miHoYo",
    story: "《原神》上线后年流水破百亿。三个交大宅男的小工作室，最终估值超千亿元，成为中国最赚钱的游戏公司之一。",
  },
  {
    id: "spacex",
    name: "可回收火箭公司",
    tagline: "造能重复使用的火箭，让发射成本降 10 倍",
    tier: "b", cost: 100, year: 2008, outcome: "win", multiplier: 12,
    real: "SpaceX",
    story: "前三次发射全部失败，公司险些破产。第四次发射成功救了 Musk 一命。如今 SpaceX 估值超 3500 亿美元。",
  },
  {
    id: "uber",
    name: "打车 App",
    tagline: "一键叫车，司机和乘客双向评价",
    tier: "a", cost: 50, year: 2011, outcome: "win", multiplier: 8,
    real: "Uber",
    story: "颠覆全球出租车行业，2019 年 IPO 估值 824 亿美元。虽然长期亏损争议不断，但早期投资人依然获得巨额回报。",
  },
  {
    id: "openai",
    name: "通用 AI 实验室",
    tagline: "做\"安全的通用人工智能\"的非营利研究机构",
    tier: "b", cost: 100, year: 2019, outcome: "win", multiplier: 10,
    real: "OpenAI",
    story: "ChatGPT 之后估值火箭式上升，最新估值达 1500-3000 亿美元区间。微软的 100 亿美元投资被认为是有史以来最赚的科技投资之一。",
  },
  {
    id: "nio",
    name: "高端电动车品牌",
    tagline: "对标特斯拉的中国本土豪华电动车",
    tier: "b", cost: 100, year: 2016, outcome: "win", multiplier: 5,
    real: "蔚来 NIO",
    story: "2018 年纽约上市，2020 年股价涨 11 倍。虽然此后估值大幅回调，但早期投资人依然取得不错回报。",
  },
  {
    id: "xiaohongshu",
    name: "种草社区",
    tagline: "年轻女性分享购物心得和生活方式的 App",
    tier: "seed", cost: 20, year: 2014, outcome: "win", multiplier: 8,
    real: "小红书 XHS",
    story: "从海外购物攻略起家的小工具，演变为月活超 3 亿的内容社区，最新估值约 200 亿美元。",
  },
  {
    id: "doordash",
    name: "餐厅外卖配送",
    tagline: "把任何餐厅的菜送到你门口",
    tier: "a", cost: 50, year: 2014, outcome: "win", multiplier: 7,
    real: "DoorDash",
    story: "斯坦福学生项目起步，2020 年 IPO 当天股价暴涨 86%，市值超 700 亿美元。",
  },

  // ================= 中等结局 (MID) =================
  {
    id: "groupon",
    name: "团购网站",
    tagline: "每天一个超低价团购，城市生活服务",
    tier: "a", cost: 50, year: 2010, outcome: "mid", multiplier: 1.5,
    real: "Groupon",
    story: "Groupon 上市时是史上增长最快的公司之一，但模式很快被复制。股价从 IPO 后腰斩再腰斩，最终市值只剩零头。",
  },
  {
    id: "fitbit",
    name: "运动手环",
    tagline: "戴在手腕上的健康数据追踪器",
    tier: "a", cost: 50, year: 2012, outcome: "mid", multiplier: 1.3,
    real: "Fitbit",
    story: "Fitbit 一度是可穿戴设备的代名词，2015 年 IPO 后市值达 100 亿美元。但 Apple Watch 来了之后增长停滞，2021 年被 Google 以 21 亿美元收购。",
  },
  {
    id: "snap",
    name: "阅后即焚社交",
    tagline: "发出去的照片会自动消失的 App",
    tier: "a", cost: 50, year: 2014, outcome: "mid", multiplier: 1.8,
    real: "Snap Inc.",
    story: "Snap 拒绝了 Facebook 30 亿美元收购，自己上市了。虽然没有成为下一个 Meta，但仍是有数亿用户的社交平台，给早期投资人不错的回报。",
  },
  {
    id: "gopro",
    name: "极限运动相机",
    tagline: "冲浪、跳伞时戴在头上的小相机",
    tier: "seed", cost: 20, year: 2012, outcome: "mid", multiplier: 1.2,
    real: "GoPro",
    story: "GoPro 2014 年上市后股价一度涨到 90 美元，但硬件故事难以为继，如今股价不到 2 美元。早期投资人勉强保本退出。",
  },
  {
    id: "robinhood",
    name: "零佣金股票券商",
    tagline: "让年轻人在手机上免费买卖股票",
    tier: "a", cost: 50, year: 2017, outcome: "mid", multiplier: 1.5,
    real: "Robinhood",
    story: "GameStop 散户大战的舞台。2021 年 IPO 估值 320 亿美元，之后股价腰斩，但近年来逐步回升。",
  },
  {
    id: "blueapron",
    name: "净菜配送",
    tagline: "每周配送预先称好的食材和食谱",
    tier: "seed", cost: 20, year: 2012, outcome: "mid", multiplier: 0.8,
    real: "Blue Apron",
    story: "巅峰估值 20 亿美元，IPO 后一路下跌，2023 年被收购退市。早期投资人小赚出场，后期投资人血亏。",
  },
  {
    id: "clubhouse",
    name: "音频聊天 App",
    tagline: "邀请制的实时语音聊天室",
    tier: "a", cost: 50, year: 2021, outcome: "mid", multiplier: 0.5,
    real: "Clubhouse",
    story: "疫情期间爆红，A16Z 给到 40 亿美元估值。但热度退去后用户大量流失，估值大幅缩水。",
  },

  // ================= 翻车 (LOSSES) =================
  {
    id: "theranos",
    name: "血液检测黑科技",
    tagline: "一滴血就能检测 200 多种疾病",
    tier: "b", cost: 100, year: 2014, outcome: "loss", multiplier: 0,
    real: "Theranos",
    story: "估值峰值 90 亿美元的医疗独角兽，创始人 Elizabeth Holmes 登上福布斯封面。结果整个技术是骗局，公司归零，创始人入狱 11 年。",
  },
  {
    id: "wework",
    name: "共享办公空间",
    tagline: "我们不是租办公室的，我们是科技公司",
    tier: "b", cost: 100, year: 2017, outcome: "loss", multiplier: 0.1,
    real: "WeWork",
    story: "孙正义重金加持，估值最高 470 亿美元的\"科技公司\"。结果 IPO 招股书一公开，估值崩到 80 亿。2023 年正式破产，VC 几乎血本无归。",
  },
  {
    id: "ofo",
    name: "共享单车",
    tagline: "扫码就能骑走的小黄车，遍布每个街角",
    tier: "a", cost: 50, year: 2017, outcome: "loss", multiplier: 0,
    real: "ofo 小黄车",
    story: "估值最高时超过 200 亿元人民币，资本疯狂加注。最终因烧钱过快、押金挪用问题崩盘，1500 万用户押金至今没退。",
  },
  {
    id: "ftx",
    name: "加密货币交易所",
    tagline: "最快、最安全、用户体验最好的加密交易所",
    tier: "b", cost: 100, year: 2021, outcome: "loss", multiplier: 0,
    real: "FTX",
    story: "红杉、淡马锡、软银愿景基金联合背书，估值 320 亿美元。CEO SBF 是华尔街新王。结果是史上最大金融欺诈之一，公司归零，SBF 被判 25 年。",
  },
  {
    id: "quibi",
    name: "短视频流媒体",
    tagline: "好莱坞品质，专为手机竖屏设计的 10 分钟短剧",
    tier: "b", cost: 100, year: 2020, outcome: "loss", multiplier: 0.05,
    real: "Quibi",
    story: "融资 17.5 亿美元，DreamWorks 创始人亲自下场。结果上线 6 个月就关门，成为科技史上最贵的失败案例之一。",
  },
  {
    id: "juicero",
    name: "智能榨汁机",
    tagline: "400 美元一台的 WiFi 榨汁机，配套使用专属果包",
    tier: "seed", cost: 20, year: 2016, outcome: "loss", multiplier: 0,
    real: "Juicero",
    story: "融资 1.2 亿美元的\"硅谷之耻\"。结果记者发现，用手挤果包跟用机器榨出来的果汁一样多。公司迅速倒闭。",
  },
  {
    id: "magic_leap",
    name: "AR 眼镜",
    tagline: "比 Hololens 更牛的混合现实头显",
    tier: "b", cost: 100, year: 2016, outcome: "loss", multiplier: 0.2,
    real: "Magic Leap",
    story: "Google、阿里巴巴等加持，融资 35 亿美元，估值 67 亿。产品发布后被吐槽体验远不如演示视频，估值暴跌 90%。",
  },
  {
    id: "moviepass",
    name: "电影院月卡",
    tagline: "每月 9.95 美元，每天看一部电影",
    tier: "seed", cost: 20, year: 2017, outcome: "loss", multiplier: 0,
    real: "MoviePass",
    story: "用户数三个月从 2 万涨到 200 万，但每张票都在亏钱。一年烧光所有融资，2019 年破产。",
  },
  {
    id: "luckin",
    name: "互联网咖啡品牌",
    tagline: "用 App 和补贴模式干掉星巴克",
    tier: "a", cost: 50, year: 2018, outcome: "loss", multiplier: 0.3,
    real: "瑞幸咖啡（造假版）",
    story: "2020 年自曝财务造假 22 亿元，纳斯达克退市，市值蒸发数十亿美元。注：瑞幸后来重组并在粉单市场恢复，但当时投资人血亏。",
  },
  {
    id: "pets_com",
    name: "宠物用品电商",
    tagline: "网上买宠物粮食，48 小时送到家",
    tier: "a", cost: 50, year: 1999, outcome: "loss", multiplier: 0.05,
    real: "Pets.com",
    story: "互联网泡沫的标志性翻车。1999 年 IPO，2000 年破产。从 IPO 到清算只用了 9 个月。",
  },
  {
    id: "houseparty",
    name: "群体视频聊天",
    tagline: "和好友一起进行多人视频派对",
    tier: "seed", cost: 20, year: 2019, outcome: "loss", multiplier: 0.1,
    real: "Houseparty",
    story: "疫情爆发时下载量暴涨 70 倍，被视为下一个独角兽。但热度退去后用户流失严重，2021 年被 Epic Games 关闭。",
  },
  {
    id: "jia",
    name: "互联网生态电视",
    tagline: "汽车、手机、电视、影视的生态化反",
    tier: "b", cost: 100, year: 2015, outcome: "loss", multiplier: 0,
    real: "乐视网 LeTV",
    story: "贾跃亭的\"为梦想窒息\"。乐视生态资金链断裂，公司退市，创始人远赴美国造车至今未归。早期投资人血本无归。",
  },
];

export const CORNERS: readonly Corner[] = [
  {
    id: "corner_start",
    name: "START",
    tagline: "每经过一次 LP 注资 +$10M",
    type: "start",
  },
  {
    id: "corner_lp",
    name: "LP MEETING",
    tagline: "GP 述职：组合亏损则被撤资 -$15M",
    type: "lp_check",
  },
  {
    id: "corner_demo",
    name: "DEMO DAY",
    tagline: "路演成功，LP 加注 +$20M",
    type: "free_dd",
  },
  {
    id: "corner_crisis",
    name: "BLACK SWAN",
    tagline: "黑天鹅：基金管理费损失 + 持仓折损",
    type: "black_swan",
  },
];
